#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(pwd)"

mkdir -p docs/api docs/cli scripts

cat >mkdocs.yml <<'EOF'
site_name: ExecTunnel
site_description: SOCKS5 tunnel over Kubernetes exec/WebSocket channels
site_url: "https://ExecTunnel.com"
repo_url: "https://github.com/Khodaparastan/ExecTunnel"
repo_name: "ExecTunnel"

theme:
    name: material
    palette:
      scheme: slate
    features:
        - navigation.sections
        - navigation.expand
        - navigation.indexes
        - content.code.copy
        - search.suggest
        - search.highlight

plugins:
    - search
    - markdownmermaid
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_source: false
                    show_root_heading: true
                    show_root_toc_entry: true
                    inherited_members: true
                    separate_signature: true
                    show_signature_annotations: true
                    members_order: source
                    docstring_style: google

markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.highlight

nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Configuration: configuration.md
    - Architecture: architecture.md
    - Protocol: protocol.md
    - Production: production.md
    - Troubleshooting: troubleshooting.md
    - CLI:
        - Overview: cli/index.md
    - API:
        - Overview: api/index.md
EOF

cat >docs/index.md <<'EOF'
# ExecTunnel

ExecTunnel provides a SOCKS5 tunnel over Kubernetes exec/WebSocket channels for restricted environments.

## Documentation sections

* Getting Started
* Configuration
* Architecture
* Protocol
* Production
* Troubleshooting
* CLI reference
* API reference
EOF

cat >docs/getting-started.md <<'EOF'
# Getting Started

## Requirements

* Python 3.12+
* Access to the Kubernetes exec/WebSocket endpoint or raw WebSocket URL
* A target environment where the remote agent can be started

## Basic tunnel

```bash
exectunnel tunnel
```

## Raw WebSocket mode

```bash
exectunnel ws wss://example.invalid/path
```

## Use the local SOCKS5 proxy

```bash
export https_proxy=socks5://127.0.0.1:1080
export http_proxy=socks5://127.0.0.1:1080
```
EOF

cat >docs/configuration.md <<'EOF'
# Configuration

ExecTunnel is configured through CLI flags and environment variables.

## Main areas

* WebSocket connection
* reconnect behavior
* SOCKS5 bind address and port
* bootstrap delivery mode
* DNS forwarding
* UDP relay tuning
EOF

cat >docs/architecture.md <<'EOF'
# Architecture

## Layers

* `protocol` — frame codec, IDs, enums
* `transport` — TCP and UDP bridging
* `proxy` — SOCKS5 server and UDP associate handling
* `session` — bootstrap, reconnect, orchestration
* `observability` — logging, metrics, tracing
* `cli` — commands and dashboards

## Runtime flow

1. Start local SOCKS5 server
2. Establish WebSocket exec session
3. Bootstrap the remote agent
4. Wait for `AGENT_READY`
5. Relay TCP and UDP traffic through framed messages
6. Reconnect on transport failure
EOF

cat >docs/protocol.md <<'EOF'
# Protocol

ExecTunnel uses newline-delimited framed messages over the Kubernetes exec/WebSocket channel.

## High-level frame types

* `CONN_OPEN`
* `CONN_ACK`
* `DATA`
* `CONN_CLOSE`
* `UDP_OPEN`
* `UDP_DATA`
* `UDP_CLOSE`
* `ERROR`
* `KEEPALIVE`
* `AGENT_READY`
EOF

cat >docs/production.md <<'EOF'
# Production

## Recommendations

* Bind SOCKS5 to loopback unless exposure is intentional
* Use manager mode for supervised multi-tunnel deployments
* Tune reconnect behavior for your environment
* Prefer the Go agent where Python 3.12 is unavailable on target pods
* Monitor logs and metrics for reconnect churn and ACK timeout patterns
EOF

cat >docs/troubleshooting.md <<'EOF'
# Troubleshooting

## Common issues

### Agent never becomes ready

Check:

* remote Python availability
* bootstrap delivery mode
* pod shell behavior
* connectivity to fetch URL if using fetch mode

### SOCKS5 client fails to connect

Check:

* local bind host and port
* whether the tunnel session reached healthy state
* reconnect / ACK timeout behavior
EOF

cat >docs/cli/index.md <<'EOF'
# CLI Reference

This section is autogenerated from command help output.

Generated files are placed under this directory by the docs generator.
EOF

cat >docs/api/index.md <<'EOF'
# API Reference

This section is autogenerated from Python modules using `mkdocstrings`.

Generated files are placed under this directory by the docs generator.
EOF

cat >scripts/generate_docs.py <<'EOF'
#!/usr/bin/env python3
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
API_DIR = DOCS_DIR / "api"
CLI_DIR = DOCS_DIR / "cli"

API_MODULES = [
    "exectunnel",
    "exectunnel.defaults",
    "exectunnel.exceptions",
    "exectunnel.protocol",
    "exectunnel.protocol.enums",
    "exectunnel.protocol.frames",
    "exectunnel.protocol.ids",
    "exectunnel.transport",
    "exectunnel.transport.tcp",
    "exectunnel.transport.udp",
    "exectunnel.proxy",
    "exectunnel.proxy.config",
    "exectunnel.proxy.request",
    "exectunnel.proxy.server",
    "exectunnel.proxy.udp_relay",
    "exectunnel.session",
    "exectunnel.session.session",
    "exectunnel.observability",
    "exectunnel.observability.logging",
    "exectunnel.observability.metrics",
    "exectunnel.observability.tracing",
]

CLI_COMMANDS = [
    [],
    ["tunnel"],
    ["ws"],
    ["manager"],
    ["config"],
    ["config", "show"],
    ["config", "validate"],
    ["status"],
]

def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)

def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

def module_to_doc_path(module: str) -> Path:
    rel = module.replace(".", "/") + ".md"
    return API_DIR / rel

def generate_api_pages() -> list[tuple[str, str]]:
    nav_entries: list[tuple[str, str]] = []
    for module in API_MODULES:
        out_path = module_to_doc_path(module)
        content = f"# `{module}`\n\n::: {module}\n"
        write_text(out_path, content)
        nav_entries.append((module, out_path.relative_to(DOCS_DIR).as_posix()))
    return nav_entries

def command_slug(parts: list[str]) -> str:
    if not parts:
        return "root"
    return "-".join(parts)

def command_title(parts: list[str]) -> str:
    if not parts:
        return "exectunnel"
    return "exectunnel " + " ".join(parts)

def run_help(parts: list[str]) -> str:
    cmd = [sys.executable, "-m", "exectunnel.cli", *parts, "--help"]
    env = os.environ.copy()
    env["TERM"] = "dumb"
    env["NO_COLOR"] = "1"
    proc = subprocess.run(
        cmd,
        cwd=REPO_ROOT,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    )
    return proc.stdout

def generate_cli_pages() -> list[tuple[str, str]]:
    nav_entries: list[tuple[str, str]] = []
    for parts in CLI_COMMANDS:
        slug = command_slug(parts)
        title = command_title(parts)
        out_path = CLI_DIR / f"{slug}.md"
        help_text = run_help(parts)
        content = f"# `{title}`\n\n```text\n{help_text}\n```\n"
        write_text(out_path, content)
        nav_entries.append((title, out_path.relative_to(DOCS_DIR).as_posix()))
    return nav_entries

def generate_api_index() -> None:
    lines = [
        "# API Reference",
        "",
        "## Main modules",
        "",
    ]
    for module in API_MODULES:
        rel = module.replace(".", "/") + ".md"
        lines.append(f"* [`{module}`]({rel})")
    lines.append("")
    write_text(API_DIR / "index.md", "\n".join(lines))

def generate_cli_index() -> None:
    lines = [
        "# CLI Reference",
        "",
        "## Commands",
        "",
    ]
    for parts in CLI_COMMANDS:
        slug = command_slug(parts)
        title = command_title(parts)
        lines.append(f"* [`{title}`]({slug}.md)")
    lines.append("")
    write_text(CLI_DIR / "index.md", "\n".join(lines))

def main() -> int:
    ensure_dir(API_DIR)
    ensure_dir(CLI_DIR)

    api_entries = generate_api_pages()
    cli_entries = generate_cli_pages()
    generate_api_index()
    generate_cli_index()

    print(f"Generated {len(api_entries)} API pages")
    print(f"Generated {len(cli_entries)} CLI pages")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
EOF

chmod +x scripts/generate_docs.py

python scripts/generate_docs.py
python -m mkdocs build

echo
echo "Documentation generated successfully."
echo "To preview locally, run:"
echo "  python -m mkdocs serve"
echo
echo "Built site is in:"
echo "  ${ROOT_DIR}/site"
