apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exectunnel

commonLabels:
  app.kubernetes.io/part-of: exectunnel
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: exectunnel
    newName: exectunnel
    newTag: latest
