apiVersion: v1
kind: Service
metadata:
  name: exectunnel
  namespace: exectunnel
  labels:
    app.kubernetes.io/name: exectunnel
    app.kubernetes.io/component: tunnel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: exectunnel
  ports:
    - name: socks
      port: 1080
      targetPort: 1080
      protocol: TCP
